#ifndef H_CONFIGS
#define H_CONFIGS

#define BL_WORKSPACE "workspace.json"
#define BL_WORKSPACE_WO_EXT "workspace"
#define BL_WORKSPACE_ARRAY_LIMIT 101
#define BL_WORKSPACE_ANS_DEFAULT "ans"
#define BL_WORKSPACE_MAX_VARLENGTH 20
#define BL_WORKSPACE_MAX_DIM 3
#define BL_WORSKPACE_MAX_RAW_SIZE 16777216

#endif