#ifndef H_PROGRAMS
#define H_PROGRAMS

static const char *programs =
    "["
      "{"
        "\"name\": \"s11toswr\","
        "\"desc\": \"convert microwave/rf S11 parameters to standing wave ratio (SWR)\","
        "\"vers\": ["
        /*        */"{\"num\":\"1.0.0\", \"msg\":\"initial release\"},"
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"irint formatting in shortest way\"}"
        /*      */"],"
        "\"pargs\": ["
        /*        */"{\"name\":\"s11\", \"minc\":1, \"maxc\":100, \"desc\":\"reflection coefficient (S11) value(s)\"}"
        /*       */"],"
        "\"oargs\": ["
        /*        */""
        /*       */"],"
        "\"opts\": ["
        /*       */"{\"short\":\"d\", \"long\":\"db\", \"desc\":\"parse S11 value(s) in decibel [dB]\"}"
        /*      */"]"
      "},"
      "{"
        "\"name\": \"wslist\","
        "\"desc\": \"list workspace\","
        "\"vers\": ["
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"initial release\"},"
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"print out single element value\"}"
        /*      */"],"
        "\"pargs\": ["
        /*        */""
        /*       */"],"
        "\"oargs\": ["
        /*        */""
        /*       */"],"
        "\"opts\": ["
        /*       */"{\"short\":\"h\", \"long\":\"history\", \"desc\":\"list history\"}"
        /*      */"]"
      "}"
    "]";

#endif