#ifndef H_PROGRAMS
#define H_PROGRAMS

static const char *programs =
    "["
      "{"
        "\"name\": \"wslist\","
        "\"desc\": \"list workspace\","
        "\"vers\": ["
        /*        */"{\"num\":\"1.0.0\", \"msg\":\"initial release\"},"
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"print out single element value\"},"
        /*        */"{\"num\":\"1.2.0\", \"msg\":\"print limited number variable values also\"},"
        /*        */"{\"num\":\"1.3.0\", \"msg\":\"improve readability of output\"}"
        /*      */"],"
        "\"pargs\": ["
        /*        */""
        /*       */"],"
        "\"oargs\": ["
        /*        */""
        /*       */"],"
        "\"opts\": ["
        /*       */"{\"short\":\"h\", \"long\":\"history\", \"desc\":\"list history\"}"
        /*      */"]"
      "},"
      "{"
        "\"name\": \"linspace\","
        "\"desc\": \"generate linearly spaced array\","
        "\"vers\": ["
        /*        */"{\"num\":\"1.0.0\", \"msg\":\"initial release\"},"
        /*        */"{\"num\":\"1.0.1\", \"msg\":\"minimum interval number check\"},"
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"print large arrays into file\"}"
        /*      */"],"
        "\"pargs\": ["
        /*        */"{\"name\":\"a\", \"minc\":1, \"maxc\":1, \"desc\":\"starting value of the sequence\"},"
        /*        */"{\"name\":\"b\", \"minc\":1, \"maxc\":1, \"desc\":\"end value of the seqeunce (included)\"},"
        /*        */"{\"name\":\"N\", \"minc\":1, \"maxc\":1, \"desc\":\"number of points\"}"
        /*       */"],"
        "\"oargs\": ["
        /*        */""
        /*       */"],"
        "\"opts\": ["
        /*      */"]"
      "},"
      "{"
        "\"name\": \"s11toswr\","
        "\"desc\": \"convert microwave/rf S11 parameters to standing wave ratio (SWR)\","
        "\"vers\": ["
        /*        */"{\"num\":\"1.0.0\", \"msg\":\"initial release\"},"
        /*        */"{\"num\":\"1.1.0\", \"msg\":\"print formatting in shortest way\"},"
        /*        */"{\"num\":\"1.2.0\", \"msg\":\"print out in column-wise sequence\"}"
        /*      */"],"
        "\"pargs\": ["
        /*        */"{\"name\":\"s11\", \"minc\":1, \"maxc\":100, \"desc\":\"reflection coefficient (S11) value(s)\"}"
        /*       */"],"
        "\"oargs\": ["
        /*        */""
        /*       */"],"
        "\"opts\": ["
        /*       */"{\"short\":\"d\", \"long\":\"db\", \"desc\":\"parse S11 value(s) in decibel [dB]\"}"
        /*      */"]"
      "}"
    "]";

#endif